### ISSUE TITLE
Tests fail if use BEMHTML

### ISSUE THREAD

**Issue by blond** [bem/bem-core#1181]
If run `BEM_TEMPLATE_ENGINE=BEMHTML magic run tests` then the build will fail.

```
10:40:28.368 - [failed] [desktop.tests/jquery__event_type_pointernative/simple/simple.html] bemjson-to-html
10:40:28.372 - build failed
10:40:28.521 - [failed] [desktop.tests/i18n/simple/.tmp.bemhtml.ru.js] bemhtml-i18n
10:40:28.521 - [failed] [desktop.tests/i18n/simple/simple.ru.html] bemjson-to-html
10:40:28.521 - [failed] [desktop.tests/i18n/simple/.tmp.bemhtml.en.js] bemhtml-i18n
10:40:28.521 - [failed] [desktop.tests/i18n/simple/simple.en.html] bemjson-to-html
10:40:28.582 - [failed] [touch.tests/jquery__event_type_pointernative/simple/.tmp.bemhtml.js] bemhtml
10:40:28.582 - [failed] [touch.tests/jquery__event_type_pointerpressrelease/simple/.tmp.bemhtml.js] bemhtml
10:40:28.582 - [failed] [touch.tests/jquery__event_type_pointernative/simple/simple.html] bemjson-to-html
10:40:28.582 - [failed] [touch.tests/jquery__event_type_pointerpressrelease/simple/simple.html] bemjson-to-html
TypeError: Cannot read property 'indexOf' of undefined
    at applyc (/Users/blond/projects/bem-core/desktop.tests/jquery__event_type_pointernative/simple/.tmp.bemhtml.js:119:23)
    at __$b32 (/Users/blond/projects/bem-core/desktop.tests/jquery__event_type_pointernative/simple/.tmp.bemhtml.js:633:21)
    at applyc (/Users/blond/projects/bem-core/desktop.tests/jquery__event_type_pointernative/simple/.tmp.bemhtml.js:174:20)
    at __$b40 (/Users/blond/projects/bem-core/desktop.tests/jquery__event_type_pointernative/simple/.tmp.bemhtml.js:735:5)
    at applyc (/Users/blond/projects/bem-core/desktop.tests/jquery__event_type_pointernative/simple/.tmp.bemhtml.js:199:20)
    at __$b32 (/Users/blond/projects/bem-core/desktop.tests/jquery__event_type_pointernative/simple/.tmp.bemhtml.js:650:25)
    at applyc (/Users/blond/projects/bem-core/desktop.tests/jquery__event_type_pointernative/simple/.tmp.bemhtml.js:174:20)
    at __$b40 (/Users/blond/projects/bem-core/desktop.tests/jquery__event_type_pointernative/simple/.tmp.bemhtml.js:735:5)
    at applyc (/Users/blond/projects/bem-core/desktop.tests/jquery__event_type_pointernative/simple/.tmp.bemhtml.js:199:20)
    at __$lb__$98 (/Users/blond/projects/bem-core/desktop.tests/jquery__event_type_pointernative/simple/.tmp.bemhtml.js:710:21)
```

**Comment by blond** [comment]
If build BEMHTML file in dev mode then everything works well.

**Comment by blond** [comment]
The problem with this code: https://github.com/bem/bem-core/blob/v2/common.blocks/jquery/__event/_type/jquery__event_type_pointernative.tests/simple.blocks/test-pointer/test-pointer.bemhtml#L8-L13
