### ISSUE TITLE
Building JS doesn't work

### ISSUE THREAD

**Issue by varya** [bem/bem-core#155]
```
12:14:22.124 - info: [t] Build time for "desktop.bundles/001-simple-block/001-simple-block.browser.js+bemhtml" [5]: 26ms
12:14:22.125 - info: [t] Build total for "desktop.bundles/001-simple-block/_001-simple-block.js": 235ms
12:14:22.139 - warn: *** HTTP error: 500, TypeError: Object [object Object] has no method 'filterPrefixes'
    at exports.techMixin.getBuildResult [as __base] (/Users/toivonen/Work/bem-js-tutorial/libs/bem-core/.bem/techs/vanilla.js.js:49:22)
    at exports.techMixin.getBuildResult (/Users/toivonen/Work/bem-js-tutorial/libs/bem-core/.bem/techs/browser.js.js:36:29)
    at res.(anonymous function) (/Users/toivonen/Work/bem-js-tutorial/node_modules/bem/node_modules/inherit/lib/inherit.js:28:32)
    at exports.techMixin.getBuildResult (/Users/toivonen/Work/bem-js-tutorial/libs/bem-core/.bem/techs/browser.js+bemhtml.js:22:21)
    at res.(anonymous function) [as getBuildResult] (/Users/toivonen/Work/bem-js-tutorial/node_modules/bem/node_modules/inherit/lib/inherit.js:28:32)
    at /Users/toivonen/Work/bem-js-tutorial/node_modules/bem/lib/tech/v2.js:284:50
    at _fulfilled (/Users/toivonen/Work/bem-js-tutorial/node_modules/bem/node_modules/q/q.js:1020:54)
    at resolvedValue.promiseDispatch.done (/Users/toivonen/Work/bem-js-tutorial/node_modules/bem/node_modules/q/q.js:1050:30)
    at makePromise.promise.promiseDispatch (/Users/toivonen/Work/bem-js-tutorial/node_modules/bem/node_modules/q/q.js:642:13)
    at Object._onImmediate (/Users/toivonen/Work/bem-js-tutorial/node_modules/bem/node_modules/q/q.js:521:44)
    at processImmediate [as _immediateCallback] (timers.js:330:15)
From previous event:
    at Cmd.exports.Cmd.Cmd._do (/Users/toivonen/Work/bem-js-tutorial/node_modules/bem/node_modules/coa/lib/cmd.js:424:14)
    at /Users/toivonen/Work/bem-js-tutorial/node_modules/bem/node_modules/coa/lib/cmd.js:510:22
    at /Users/toivonen/Work/bem-js-tutorial/node_modules/bem/node_modules/coa/node_modules/q/q.js:893:30
    at /Users/toivonen/Work/bem-js-tutorial/node_modules/bem/node_modules/coa/node_modules/q/q.js:360:35
```

**Comment by varya** [comment]
Возможно, это для project-stub баг?

**Comment by arikon** [comment]
Скорее всего project-stub. По логу видно, что здесь случается миск технологий V1 и V2.

/cc @tadatuta @diunko

**Comment by tadatuta** [comment]
разобрались
