### ISSUE TITLE
Update from v2.0.0 issue

### ISSUE THREAD

**Issue by apsavin** [bem/bem-core#736]
I'm updating my project from v2.0.0 (d878fb8665e9aad8532c0b5318a7220654bd028c) to the latest (0c5d7fc34faf839098817325c07a4b79a2f7cabc) bem-core version.
I've got an error during `bem make`:

```
Error: Only literal or function is allowed in template's body at 1308:14
content()({
              ^
    at Compiler.assert (/Users/apsavin/Sites/hippo/app/Resources/views/libs/bem-core/node_modules/bem-xjst/node_modules/xjst/lib/xjst/compiler/base.js:183:9)
    at Compiler.transformTemplates (/Users/apsavin/Sites/hippo/app/Resources/views/libs/bem-core/node_modules/bem-xjst/node_modules/xjst/lib/xjst/compiler/base.js:651:8)
    at Array.map (native)
    at Compiler.translate (/Users/apsavin/Sites/hippo/app/Resources/views/libs/bem-core/node_modules/bem-xjst/node_modules/xjst/lib/xjst/compiler/base.js:204:41)
    at Object.translate (/Users/apsavin/Sites/hippo/app/Resources/views/libs/bem-core/node_modules/bem-xjst/node_modules/xjst/lib/xjst/api.js:16:40)
    at Compiler.translate (/Users/apsavin/Sites/hippo/app/Resources/views/libs/bem-core/node_modules/bem-xjst/lib/bemhtml/compiler.js:121:35)
    at Compiler.generate (/Users/apsavin/Sites/hippo/app/Resources/views/libs/bem-core/node_modules/bem-xjst/lib/bemhtml/compiler.js:707:14)
    at Object.generate (/Users/apsavin/Sites/hippo/app/Resources/views/libs/bem-core/node_modules/bem-xjst/lib/bemhtml/api.js:16:40)
    at exports.techMixin.getCompiledResult (/Users/apsavin/Sites/hippo/app/Resources/views/libs/bem-core/.bem/techs/bemhtml.js:46:24)
    at _fulfilled (/Users/apsavin/Sites/hippo/node_modules/q/q.js:798:54)
```

After some investigation, I changed a bit Compiler from xjst and it's became clear to me, that problem is in the following template: 

``` js
block('a').elem('b')(
    tag()('span'),

    content()({
        block: 'c',
        content: this.ctx.content
    })
);
```

Do I need to wrap all the similar templates' content into functions like this now?

``` js
block('a').elem('b')(
    tag()('span'),

    content()(function () { 
        return {
            block: 'c',
            content: this.ctx.content
        };
    })
);
```

**Comment by tadatuta** [comment]
yes, you are to wrap into functions all templates with `this.anyField` or `apply*()` calls.

that was done to garantee that templates in dev and production modes are the same.

otherwise in dev mode expressions like `content()(this.ctx.something)` start evaluating with `this.ctx.something` and `this` points to another object at that moment so you get `undefined`.

**Comment by jifeon** [comment]
@tadatuta so you should fix your documentation, because this https://en.bem.info/technology/bemhtml/v2/bemhtml-js-syntax/#arbitrary-conditions asserts that I can use `match` with `ctx` without any functions

**Comment by tadatuta** [comment]
@jifeon done in https://github.com/bem/bem-core/commit/254e3e4451d3c97103c8e5cf03da24cb0f0275c7
Thank you!
