### ISSUE TITLE
[browser.js Tech] call [js.js Tech] wrong interface

### ISSUE THREAD

**Issue by gurobokum** [bem/bem-core#868]
In the technology bem-core/.bem/techs/browser.js.js

``` javascript
26                                                                                                                                                                                                
27     getYmChunk : function() {                                                                                                                                                                  
28         var ymRelPath = this.__base.apply(this, arguments);                                                                                                                                    
29         return this.getBuildResultChunk(ymRelPath);                                                                                                                                            
30     }                                                                                                                                                                                          
31                                                                                                                                                                                                
32 };    
```

but in extended technology js (API V1)

``` javascript
 9     getBuildResultChunk: function(relPath, path, suffix) {                                                                                                                                     
10                                                                                                                                                                                                
11         return [                                                                                                                                                                               
12             '/* ' + relPath + ': begin */ /**/',                                                                                                                                               
13             FS.readFileSync(path) + ';',                                                                                                                                                       
14             '/* ' + relPath + ': end */ /**/',                                                                                                                                                 
15             '\n'].join('\n');                                                                                                                                                                  
16                                                                                                                                                                                                
17     }                                                                                                                                                                                          
18 });
```

And I get 

``` bash
19:41:24.185 - info: [t] Build time for "desktop.bundles/items/items.bemhtml" [1]: 1064ms
TypeError: path must be a string
    at Object.fs.openSync (fs.js:432:18)
    at Object.fs.readFileSync (fs.js:289:15)
    at exports.Tech.INHERIT.getBuildResultChunk (/home/***/workspace/***/frontend/node_modules/bem/lib/techs/js.js:13:16)
```

Should I use some special treeish?
bem-core's branch is v2, or may be browser.js is obsolete?
How should i do?
Thanks

**Comment by gurobokum** [comment]
c087563532a0cbb59fceb1368388f0a8a57745cb

**Comment by tadatuta** [comment]
@JIoJIaJIu Can you please push your project to github? I think the issue is somewhere on your side as `browser.js` tech works fine for me.

**Comment by veged** [comment]
@JIoJIaJIu ping ;-)

**Comment by gurobokum** [comment]
Прошу прощения, упустил комментарий)
К сожалению, не могу скинуть конфигурацию проекта - он в приватной репе
Использую bem-tools для сборки
bem-core

``` javascript
 9         return {                                                                                                                                                                               
10             'bem-core': {                                                                                                                                                                      
11                 type: 'git',                                                                                                                                                                   
12                 url: 'git@github.com:JIoJIaJIu/bem-core.git',                                                                                                                                  
13                 treeish: 'v2'                                                                                                                                                                  
14             },  
```

fork - https://github.com/JIoJIaJIu/bem-core

desktop.bundles/

``` javascript
12         //js                                                                                                                                                                                   
13         'js': 'v2/js',                                                                                                                                                                         
14         'vanilla.js': '../../bem-core/.bem/techs/vanilla.js.js',                                                                                                                               
15         'browser.js': '../../bem-core/.bem/techs/browser.js.js',                                                                                                                               
16         'browser.js+bemhtml': '../../bem-core/.bem/techs/browser.js+bemhtml.js'  
```

Использование BEM.api

``` javascript
16 var techs = [                                                                                                                                                                                  
17     'node_modules/bem/lib/techs/v2/css.js',                                                                                                                                                    
18     '.bem/techs/priv.js.js',                                                                                                                                                                   
19     './bem-core/.bem/techs/bemhtml.js',                                                                                                                                                        
20     'bem-core/.bem/techs/vanilla.js.js',                                                                                                                                                       
21     'bem-core/.bem/techs/browser.js.js',                                                                                                                                                       
22     'bem-core/.bem/techs/browser.js+bemhtml.js'                                                                                                                                                
23 ];                                                                                                                                                                                             
24                                                                                                                                                                                                
25 console.log('tech:', techs.join('\ntech: '));                                                                                                                                                  
26                                                                                                                                                                                                
27 var promise = BEM.build({                                                                                                                                                                      
28         outputDir: 'merge',                                                                                                                                                                    
29         outputName: 'index',                                                                                                                                                                   
30         outputLevel: B.createLevel('desktop.bundles/'),                                                                                                                                        
31         declaration: 'desktop.bundles/merge/merge.deps.js',                                                                                                                                    
32         level: levels,                                                                                                                                                                         
33         tech: techs                                                                                                                                                                            
34     });  
```

**Comment by tadatuta** [comment]
См. комментарии в https://github.com/bem/bem-core/pull/878
