### ISSUE TITLE
Feedback for "Быстрый старт по BEMHTML"

### ISSUE THREAD

**Issue by VVE** [bem/bem-core#916]
Здравствуйте! 
Повторяю урок на локальном компьютере в Win-7. 
1. Начну с конца: на шаге 4 получил в браузере ошибки (ниже), прошу подсказать, в чем моя ошибка:
AssertionError: mode literal predicates can't have arguments
   at Compiler.getBinop (C:\Users\1\YandexDisk\landings\project-hello\node_modules\enb-bemxjst\node_modules\bem-xjst\lib\bemhtml\compiler.js:217:12)
   at Compiler.replaceCustom (C:\Users\1\YandexDisk\landings\project-hello\node_modules\enb-bemxjst\node_modules\bem-xjst\lib\bemhtml\compiler.js:282:23)
   at Controller.estraverse.replace.leave (C:\Users\1\YandexDisk\landings\project-hello\node_modules\enb-bemxjst\node_modules\bem-xjst\lib\bemhtml\compiler.js:88:18)
   at Controller.__execute (C:\Users\1\YandexDisk\landings\project-hello\node_modules\enb-bemxjst\node_modules\bem-xjst\node_modules\estraverse\estraverse.js:318:31)
   at Controller.replace (C:\Users\1\YandexDisk\landings\project-hello\node_modules\enb-bemxjst\node_modules\bem-xjst\node_modules\estraverse\estraverse.js:478:31)
   at Object.replace (C:\Users\1\YandexDisk\landings\project-hello\node_modules\enb-bemxjst\node_modules\bem-xjst\node_modules\estraverse\estraverse.js:561:27)
   at Compiler.pretranslate (C:\Users\1\YandexDisk\landings\project-hello\node_modules\enb-bemxjst\node_modules\bem-xjst\lib\bemhtml\compiler.js:76:20)
   at Compiler.translate (C:\Users\1\YandexDisk\landings\project-hello\node_modules\enb-bemxjst\node_modules\bem-xjst\lib\bemhtml\compiler.js:120:14)
   at Compiler.generate (C:\Users\1\YandexDisk\landings\project-hello\node_modules\enb-bemxjst\node_modules\bem-xjst\lib\bemhtml\compiler.js:707:14)
   at Object.generate (C:\Users\1\YandexDisk\landings\project-hello\node_modules\enb-bemxjst\node_modules\bem-xjst\lib\bemhtml\api.js:16:40).
Не знаю, нужно ли что-то приложить.
2. Наверное, текст не поправили после правки файлов. У меня на шаге 2 блок уже есть, только имя - другое и контент обернут в квадратные скобки. 
3. В начале пути в некоторых командах командной строки - кажется, лишние точка со слэшем (по крайней мере, для Win). 
Спасибо!

**Comment by tadatuta** [comment]
1. В тексте была ошибка, [исправил](https://github.com/bem/bem-core/commit/09d4d7f19d9fa077a919de2e12082f0161bac3b4), спасибо!
2. Речь о том, чтобы для тренировки создать новый, чтобы пройти весь путь с нуля.
3. Точка указывает на текущую папку. Если выполнять команды в git bash, то они должны правильно работать в такой нотации.

**Comment by VVE** [comment]
Большое спасибо!!! 
Конечно, помогло. В https://ru.bem.info/technology/bemhtml/v2/intro/#template потом тоже обновится?

**Comment by Guria** [comment]
Да, оно собирается из исходников на github и будет обязательно обновлено.
